name: Security Scan

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 6 * * 1"

permissions:
  contents: read
  security-events: write

jobs:
  trivy:
    uses: yboyer/ci-templates/.github/workflows/trivy.yml@master
